### ISSUE TITLE
Create a Better Project Readme that explains more on what the project does and how to contribute

### ISSUE THREAD

**Issue by Hudson-obai** [SpaceyaTech/Team-Berlin-React#3]
Create A Better ReadMe Explaining What The Project Is About
The Readme should also include the [product vision](https://github.com/SpaceyaTech/Team-Berlin-React/wiki/Product-Vision---Team-Berlin) and what the product is about.

**Comment by Clinton-dev** [comment]
Has anyone tackled the issue?

**Comment by jumalaw98** [comment]
@Clinton-dev not yet, you can pick it up

**Comment by jumalaw98** [comment]
@Clinton-dev would you mind if I assign you the task?

**Comment by Clinton-dev** [comment]
NO problem

**Comment by jumalaw98** [comment]
You can make update of the `pre-dev` branch, that what is updated
Then check contribution guide, when updating the readme

**Comment by Clinton-dev** [comment]
other than about section, product vision, installation and how to contribute. What else should I include?
